app <- ShinyDriver$new("../../", seed = 1)
app$snapshotInit("mytest")

app$setInputs(min_char = 0)
app$snapshot()
app$snapshot()
app$setInputs(selected = "Firmicutes")
app$snapshot()
app$setInputs(highlight = "Aerococcus")
app$snapshot()
app$snapshot()
app$setInputs(suffix = "current")
app$setInputs(sep = " ...")
app$setInputs(selected = character(0))
app$setInputs(selected = "Anaerofustis")
app$snapshot()
