# helper functions for adding arrows/segments/vectors to ordination plots

#' draw arrows/segments originating from origin point on ggplot ordination
#'
#' @param p ggplot ordination
#' @param data positions of segment endpoints on axes
#' @param styleList list of aesthetics e.g. generated by a vec_* helper
#' @param axesNames names of axes to plot
#'
#' @return ggplot
#' @noRd
ord_arrows <- function(p, data, styleList, axesNames, defaultStyles){
  args <- list(
    data = data, mapping = ggplot2::aes_string(
      xend = axesNames[1], yend = axesNames[2], x = 0, y = 0
    )
  )
  styles <- defaultStyles
  styles[names(styleList)] <- styleList
  p <- p + do.call(what = ggplot2::geom_segment, args = c(args, styles))
  return(p)
}

#' @title create ordination plot vector styling lists
#'
#' @param size width of vector
#' @param alpha opacity of vector
#' @param colour colour of vector
#' @param arrow arrow style specified with grid::arrow() or NULL for no arrow
#' @param lineend Line end style (round, butt, square).
#' @param linejoin Line join style (round, mitre, bevel).
#' @param ... further arguments passed to geom_segment
#'
#' @return list

## vector style helpers -------------------------------------------------------

#' @export
#' @rdname ord_arrows
vec_constraint <- function(
  size = 1, alpha = 0.8, colour = "brown",
  arrow = grid::arrow(
    length = grid::unit(0.005, units = "npc"), type = "closed", angle = 30
  ),
  lineend = "round", linejoin = "mitre",
  ...
){
  list(
    size = size, alpha = alpha, arrow = arrow, colour = colour,
    lineend = lineend, linejoin = linejoin, ...
  )
}

#' @export
#' @rdname ord_arrows
vec_tax_sel <- function(
  size = 0.5, alpha = 1, colour = "black",
  arrow = grid::arrow(
    length = grid::unit(0.005, units = "npc"), type = "closed", angle = 30
  ),
  lineend = "round", linejoin = "mitre",
  ...
){
  list(
    size = size, alpha = alpha, arrow = arrow, colour = colour,
    lineend = lineend, linejoin = linejoin, ...
  )
}

#' @export
#' @rdname ord_arrows
vec_tax_all <- function(size = 0.5, alpha = 0.25, arrow = NULL, ...
){
  list(size = size, alpha = alpha, arrow = arrow, ...)
}




