name: Docker Image Build and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Dockerhub login
      env: 
        DOCKERHUB_USER: ${{secrets.DOCKERHUB_USER}}
        DOCKERHUB_PASS: ${{secrets.DOCKERHUB_PASS}}
      run: |
        docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
        
    - name: Build the Docker image
      run: docker build . --file docker/latest/Dockerfile --tag microviz-rocker-verse:latest
      
    - name: Docker push
      run: docker push ${{secrets.DOCKERHUB_USER}}/microviz-rocker-verse:latest
